config/routes.rb
Rails.application.routes.draw do
  root to: 'contact_files#index'
  resources :contact_files, only: %i[index create destroy] do
    resource :import, only: %i[new create], controller: 'contact_files/imports'
  end
  resources :contacts, only: :index
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/credit_card_methods.rb
module CreditCardMethods
  def save_credit_card
    self.franchise = credit_card_franchise
    self.credit_card_last_4 = credit_card.try(:last, 4)
    self.credit_card = credit_card_digest
  end

  private
  def credit_card_digest
    Digest::SHA2.hexdigest(credit_card)
  rescue
    credit_card
  end

  def credit_card_franchise
    credit_card&.credit_card_brand_name || 'Invalid franchise'
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  require 'credit_card_validations/string'
  include CreditCardMethods

  PHONE_REGEX = /\A\(\+\d{2}\) \d{3}([- ])\d{3}\1\d{2}\1\d{2}\z/.freeze
  NAME_REGEX = /\A[a-zA-Z0-9 -]*\z/.freeze

  enum status: { succeeded: 0, failed: 1 }

  belongs_to :contact_file

  validates :name, presence: true, format: { with: NAME_REGEX , multiline: true }, if: :succeeded?
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, if: :succeeded?
  validates :phone, presence: true, format: {with: PHONE_REGEX }, if: :succeeded?
  validates :address, presence: true, if: :succeeded?
  validates :credit_card, presence: true, credit_card_number: true, if: :succeeded?
  validates :date_of_birth, presence: true, if: :succeeded?
  validates_each :date_of_birth_before_type_cast, if: :succeeded? do |record, attribute, value|
    value.include?("-") ? Date.strptime(value, "%F") : Date.strptime(value, "%Y%m%d")
  rescue
    record.errors.add(:date_of_birth, :invalid)
  end

  after_initialize { status = :succeeded if new_record? }

  before_save :save_credit_card
end

app/models/contact_file.rb
class ContactFile < ApplicationRecord
  enum status: { on_hold: 0, processing: 1, failed: 2, finished: 3 }

  delegate :filename, to: :file

  belongs_to :user

  has_one_attached :file
  has_many :contacts, dependent: :destroy

  validates :headers, presence: true
  validates :file, attached: true, content_type: ['text/csv']

  after_initialize { status = :on_hold if new_record? }

  def file_path
    file.blob.service.name == :local || file.blob.service.name == :test ? ActiveStorage::Blob.service.send(:path_for, file.blob.key) : file.service_url
  end
end

app/models/user.rb
class User < ApplicationRecord
  scope :succeeded, -> { where(status: :succeeded) }
  scope :failed, -> { where(status: :failed) }

  has_many :contact_files, dependent: :destroy
  has_many :contacts, through: :contact_files

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contact_files/imports_controller.rb
module ContactFiles
  class ImportsController < ApplicationController
    before_action :set_contact_file

    def new; end

    def create
      CsvImportJob.perform_later(contact_file_id: @contact_file.id, matched_headers: import_params)
      @contact_file.processing!
      redirect_to contact_files_path, notice: 'Your file is being processed...'
    end

    private
    def set_contact_file
      @contact_file = current_user.contact_files.find(params[:contact_file_id])
    end

    def import_params
      params.require(:import).permit(:name, :email, :date_of_birth, :phone, :address, :credit_card)
    end
  end
end

app/controllers/contact_files_controller.rb
class ContactFilesController < ApplicationController
  before_action :set_contact_file, only: :destroy

  def index
    @contact_files = current_user.contact_files.order(created_at: :desc)
    @contact_file = ContactFile.new
  end

  def create
    if params[:contact_file].present?
      @contact_file = current_user.contact_files.build(contact_file_params)
      result = ContactFiles::Create.call(@contact_file)
      if result.success?
        redirect_to new_contact_file_import_path(@contact_file), notice: 'File uploaded successfully!'
      else
        redirect_to contact_files_path, alert: result.error
      end
    else
      redirect_to contact_files_path, alert: 'File needed!'
    end
  end

  def destroy
    @contact_file.destroy
    redirect_to contact_files_path, alert: 'File deleted successfully!'
  end

  private
  def contact_file_params
    params.require(:contact_file).permit(:file)
  end

  def set_contact_file
    @contact_file = current_user.contact_files.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @succeeded_contacts = current_user.contacts.succeeded.order(created_at: :desc)
    @failed_contacts = current_user.contacts.failed.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_files_helper.rb
module ContactFilesHelper
  def contact_headers
    %i[name email date_of_birth phone address credit_card]
  end

  def format_date(date)
    date&.strftime('%Y %B %d')
  end
end

app/views/contact_files/imports/new.html.erb
<h3>Select headers</h3>
<p>Match csv headers with your contact fields</p>
<%= form_for :import, url: contact_file_import_path do |f|  %>
  <% contact_headers.each_with_index do |header, i| %>
    <div class='row g-2 align-items-center mb-2'>
      <div class='col-auto' >
        <%= f.label header.to_sym, nil, class: 'form-label' %>
      </div>
      <div class='col-auto'>
        <%= f.select header.to_sym, options_for_select(@contact_file.headers, @contact_file.headers[i]), class: 'form-select' %>
      </div>
    </div>
  <% end %>
  <div class='mb-3'>
    <%= submit_tag 'Import contacts', class: 'btn btn-primary' %>      
  </div>
<% end %>

app/views/contact_files/index.html.erb
<%= form_for @contact_file do |form| %>
  <div class='mb-3' >
    <%= form.file_field :file, class: 'form-control' %>
  </div>
  <div class='mb-3' >
    <%= form.submit 'Upload', class: 'btn btn-primary' %>
  </div>
<% end %>
<h3>Contact files</h1>

<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Filename</th>
      <th scope="col">Headers</th>
      <th scope="col">Uploaded at</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @contact_files.each do |file| %>
      <tr>
        <td> <%= file.filename %> </td>
        <td> <%= "#{time_ago_in_words file.created_at} ago" %> </td>
        <td> <%= file.headers %> </td>
        <td> <%= file.status.humanize %> </td>
        <td>
          <%= link_to 'Import', new_contact_file_import_path(file), class: 'btn btn-sm btn-primary' %> 
          <%= link_to 'Delete', contact_file_path(file), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/index.html.erb
<h3>Contacts</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Succeeded</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Failed</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Date of birth</th>
          <th scope="col">Phone</th>
          <th scope="col">Address</th>
          <th scope="col">Credit card</th>
          <th scope="col">Franchise</th>
          <th scope="col">Creation date</th>
        </tr>
      </thead>
      <tbody>
        <% @succeeded_contacts.each do |contact| %>
          <tr>
            <td> <%= contact.name %> </td>
            <td> <%= contact.email %> </td>
            <td> <%= format_date(contact.date_of_birth) %> </td>
            <td> <%= contact.phone %> </td>
            <td> <%= contact.address %> </td>
            <td> <%= "***********#{contact.credit_card_last_4}" %> </td>
            <td> <%= contact.franchise %> </td>
            <td> <%= "#{time_ago_in_words contact.created_at} ago" %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Date of birth</th>
          <th scope="col">Phone</th>
          <th scope="col">Address</th>
          <th scope="col">Credit card</th>
          <th scope="col">Creation date</th>
          <th scope='col'>Errors</th>
        </tr>
      </thead>
      <tbody>
        <% @failed_contacts.each do |contact| %>
          <tr>
            <td> <%= contact.name %> </td>
            <td> <%= contact.email %> </td>
            <td> <%= format_date(contact.date_of_birth) %> </td>
            <td> <%= contact.phone %> </td>
            <td> <%= contact.address %> </td>
            <td> <%= contact.credit_card %> </td>
            <td> <%= "#{time_ago_in_words contact.created_at} ago" %> </td>
            <td> <%= contact.error_details %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Contact importer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Contact files', contact_files_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contacts', contacts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          <li class="nav-item">
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          <li class="nav-item">
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>